name: Changeset Release
author: withstudiocms
description: >
  A GitHub Action to automate release creation and notifications.

branding:
  color: "blue"
  icon: "package"

inputs:
  repository:
    description: The repository to run the release bot on.
    required: true
  CWD:
    description: The current working directory where the release bot should operate.
    required: true
  PublishedPackages:
    description: A JSON array of packages that were published in this release.
    required: true
  RoleMentionId:
    description: Optional Discord role ID to mention at the top of the message.
    required: false
  DISCORD_WEBHOOK:
    description: >
      URL of a Discord webhook for release notifications.
      To create one, follow the same steps as for the mergebot webhook.
    required: true
  SERVICE_TOKEN:
    description: >
      A GitHub token with repo and workflow permissions.
      You can use the `STUDIOCMS_SERVICE_TOKEN` secret for this.
    required: true
  NPM_TOKEN:
    description: >
      An npm token with publish permissions.
      You can use the `NPM_TOKEN` secret for this.
    required: true

runs:
  using: composite
  steps:
    - name: Run Changeset Release
      id: changesets
      uses: changesets/action@e0145edc7d9d8679003495b11f87bd8ef63c0cba # v1.5.3
      with:
        with:
            setupGitUser: true
            commit: "👷 [ci]: Version Packages"
            title: "👷 [ci]: Ready for Release"
            version: pnpm ci:version
            publish: pnpm ci:publish
        env:
          GITHUB_TOKEN: ${{ inputs.STUDIOCMS_SERVICE_TOKEN }}
          NPM_TOKEN: ${{ inputs.NPM_TOKEN }}
    
    - name: Add Label to CI PR
      if: ${{ steps.changesets.outputs.hasChangesets == 'true' }}
      run: gh pr edit "$PR_URL" --add-label "ci"
      env:
        PR_URL: ${{ steps.changesets.outputs.pull_request_url }}
        GITHUB_TOKEN: ${{ inputs.SERVICE_TOKEN }}

    - name: Initiate Release Bot
      if: ${{ steps.changesets.outputs.published == 'true' }}
      uses: ./.github/actions/releasebot/action.yml
      with:
        repository: ${{ inputs.repository }}
        CWD: ${{ inputs.CWD }}
        PublishedPackages: ${{ steps.changesets.outputs.publishedPackages }}
        DISCORD_WEBHOOK: ${{ inputs.DISCORD_WEBHOOK }}
        RoleMentionId: ${{ inputs.RoleMentionId }}

