name: Install Tools & Dependencies
description: Installs pnpm, Node.js & package dependencies

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
      with:
        version: 10.17.0

    - name: Setup Node.js based on .node-version
      uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
      with:
        node-version-file: '.node-version'
        registry-url: 'https://registry.npmjs.org'
        cache: 'pnpm'

    # Ensure npm 11.5.1 or later is installed
    - name: Update npm
      run: npm install -g npm@latest
      shell: bash

    - name: Install Dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
