name: withstudiocms First Time PR Check

on:
  workflow_call:
    secrets:
      SERVICE_TOKEN:
        description: GitHub token for permissions
        required: true
      DISCORD_WEBHOOK:
        description: webhook url for First Time PR messages
        required: true
      DISCORD_ROLE_HONOURED:
        description: roleID for Honoured
        required: true
      DISCORD_ROLE_REVERED:
        description: roleID for Revered
        required: true
      DISCORD_ROLE_EXALTED:
        description: roleID for Exalted
        required: true


jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Check if first PR merged
        id: check
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7
        with:
          github-token: ${{ secrets.SERVICE_TOKEN }}
          script: |
            if (context.payload.pull_request.merged) {
              const creator = context.payload.pull_request.user.login
              const owner = context.repo.owner
              const repo = context.repo.repo
              const res = await github.rest.search.issuesAndPullRequests({
                q: `is:pr is:closed author:${creator} repo:${owner}/${repo}`
              })

              const mergedPRs = res.data.items.filter(pr => pr.number !== context.payload.pull_request.number)

              if (mergedPRs.length === 0) {
                return {
                  isFirstPR: true
                  issueNumber: context.issue.number,
                  owner: owner,
                  repo: repo,
                  newUser: creator
                }
              } else {
                return {
                  isFirstPR: false
                }
              }
            } else {
              return {
                isFirstPR: false
              }
            }
            
      - name: Comment on PR
        if: ${{ steps.check.outputs.isFirstPR == 'true' }}
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7
        env:
          ISSUE_NUMBER: ${{ steps.check.outputs.issueNumber }}
          OWNER: ${{ steps.check.outputs.owner }}
          REPO: ${{ steps.check.outputs.repo }}
          NEW_USER: ${{ steps.check.outputs.newUser }}
        with:
          github-token: ${{ secrets.SERVICE_TOKEN }}
          script: |
            const { ISSUE_NUMBER, OWNER, REPO, NEW_USER } = process.env
            await github.rest.issues.createComment({
              issue_number: ISSUE_NUMBER,
              owner: OWNER,
              repo: REPO,
              body: `**Welcome** @${NEW_USER}, to the Contributor Squad! 🎉\n\nIf you haven't already, please join our [Discord community](https://chat.studiocms.dev), to stay in the loop for any future help we may need!`
            })
            
      - name: Send Discord Message
        if: ${{ steps.check.outputs.isFirstPR == 'true' }}
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7
        env:
          ISSUE_NUMBER: ${{ steps.check.outputs.issueNumber }}
          OWNER: ${{ steps.check.outputs.owner }}
          REPO: ${{ steps.check.outputs.repo }}
          NEW_USER: ${{ steps.check.outputs.newUser }}
          DISCORD_FTPR: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_ROLE_HONOURED: ${{ secrets.DISCORD_ROLE_HONOURED }}
          DISCORD_ROLE_REVERED: ${{ secrets.DISCORD_ROLE_REVERED }}
          DISCORD_ROLE_EXALTED: ${{ secrets.DISCORD_ROLE_EXALTED }}
        with:
          github-token: ${{ secrets.SERVICE_TOKEN }}
          script: |
            const { DISCORD_FTPR, DISCORD_ROLE_HONOURED, DISCORD_ROLE_REVERED, DISCORD_ROLE_EXALTED, OWNER, REPO, NEW_USER } = process.env
            
            await fetch(DISCORD_FTPR, {
              method: 'POST',
              headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
              },
              body: JSON.stringify({
                content: `<@&${DISCORD_ROLE_HONOURED}>, <@&${DISCORD_ROLE_REVERED}>, <@&${DISCORD_ROLE_EXALTED}>`,
                tts: false,
                embeds: [
                  {
                    "id": 661098315,
                    "description": `New '${OWNER}/${REPO}' Contributor - ${NEW_USER} has had their first PR merged! 🎉\nMerged PR: [PR# ${ISSUE_NUMBER}](https://github.com/${OWNER}/${REPO}/pull/${ISSUE_NUMBER})`,
                    "fields": [],
                    "author": {
                      "name": "StudioCMS Contributor Alert",
                      "icon_url": "https://github.com/withstudiocms/studiocms.dev/blob/main/assets/logo-discord.png?raw=true"
                    },
                    "title": "🚨 FIRST TIME CONTRIBUTOR 🚨"
                  }
                ],
                components: [],
                actions: {}
              })
            })
