name: Biome Formatter

on:
  workflow_call:
    secrets:
      STUDIOCMS_GIT_BOT_APP_ID:
        description: 'The GitHub App ID for authenticating with the GitHub API'
        required: true
      STUDIOCMS_GIT_BOT_PRIVATE_KEY:
        description: 'The GitHub App Private Key for authenticating with the GitHub API'
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    env:
      NODE_OPTIONS: "--max_old_space_size=4096"
    steps:
      - name: Setup Apollo Git Bot
        id: bot-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          app-id: ${{ secrets.STUDIOCMS_GIT_BOT_APP_ID }}
          private-key: ${{ secrets.STUDIOCMS_GIT_BOT_PRIVATE_KEY }}

      - name: Checkout Repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: true
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          token: ${{ steps.bot-token.outputs.token }}

      - name: Install Tools & Dependencies
        uses: withstudiocms/automations/.github/actions/install@2f4fab1a66855feadec9e960bdbdc4368c23aa18 # main

      - name: Run Biome formatter
        run: pnpm biome check --write .

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        with:
          commit_message: '[ci] lint'
          branch: ${{ github.event.pull_request.head.sha || github.sha }}
          commit_user_name: apollo-git-bot[bot]
          commit_user_email: 234251158+apollo-git-bot[bot]@users.noreply.github.com
          commit_author: Apollo Git Bot <234251158+apollo-git-bot[bot]@users.noreply.github.com>
